import React from "react";
import Head from "next/head";
import Image from "next/image";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-slate-900 py-10 mb-10">
        <h1 className="text-6xl text-center text-amber-400">Pokedex</h1>
      </header>

      <main className="container mx-auto mb-10">{children}</main>
    </div>
  );
};

export default Layout;
